### ISSUE TITLE
Tečajnica

### ISSUE THREAD

**Issue by zanmoskotevc** [Neophytez/t212-edavki#1]
Zdravo!

Najprej hvala za skripto. Vprašanje glede tečaja, zakaj Yahoo Finance?
Ali ne bi bilo pravilneje uporabiti ECB oz. BSI? Ali se ujemata?

https://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist-90d.xml
https://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist.xml

**Comment by Neophytez** [comment]
Sem iskal, kakšen tečaj uporablja T212, pa nisem našel. Vzel sem Yahoo Finance, ker omogoča prenos podatkov za leta nazaj. Verjamem pa, da ni pravilno, tudi tečaj se ne ujema točno.

Si morda preveril, če se ujema z ECB?

**Comment by zanmoskotevc** [comment]
Žal se ne. Ali se da uporabiti podatke iz zgornjih dveh linkov?

**Comment by Neophytez** [comment]
Drugi link je celotna zgodovina, kar je OK.

Če se ti mudi, lahko sam pretvoriš XML v CSV in daš datoteko v mapo "rate". Format naj bo isti kot v že obstoječih datotekah.

Bom pa posodobil tečaj tekom tega ali naslednjega tedna.

**Comment by Neophytez** [comment]
Podatki so sedaj iz ECB Europa (2022-2020).
