### ISSUE TITLE
XML datoteke ni v mapi output

### ISSUE THREAD

**Issue by razpotniknejcc** [Neophytez/t212-edavki#2]
Zdravo,

Najprej najlepša hvala za program.

Ko zaženem program, mi kot v navodilih napiše "Your XML file is located inside output folder.", ampak ko odprem mapo ''output'' datoteke ni v njej.

Morda kdo ve, kaj je šlo narobe?

**Comment by Neophytez** [comment]
Zdravo,

v mapi "output" ni datoteke "output.xml"?

**Comment by razpotniknejcc** [comment]
Tako je ja.

Zgolj datoteka ''.gitkeep''

**Comment by Neophytez** [comment]
Mi lahko pošlješ celoten izpis programa + nekaj vrstic svoje CSV datoteke?

Lahko kar na [mail](mailto:lenar.rahmatullin@gmail.com).

**Comment by Neophytez** [comment]
Napaka ni code-related. Pri meni se za isti CSV XML zgenerira.
