### ISSUE TITLE
Dividende

### ISSUE THREAD

**Issue by zanmoskotevc** [Neophytez/t212-edavki#4]
Zdravo!

Ali je možno dodati še podporo za uvoz izplačanih dividend?

Hvala

**Comment by Neophytez** [comment]
Pozdravljen,

ker v T212 izvozu niso na voljo vsi potrebni podatki (identifikacijska številka, naziv, naslov, država) in bi jih bilo potrebno črpati iz nekje drugje, zaenkrat podpora dividend ni predvidena.
