### ISSUE TITLE
Ne uvozi postavk, ki imajo samo nakupe

### ISSUE THREAD

**Issue by zanmoskotevc** [Neophytez/t212-edavki#5]
Zdravo!

V kolikor za določen ticker ni bilo prodaje, je ni potrebno uvažati, saj ni potreba poročati o nakupih dokler ni prodaje.
Ali se lahko v tem primeru izločijo ti tickerji?

**Comment by Neophytez** [comment]
Pozdravljen,

posodobljeno, tickerji brez market sell in limit sell se ignorirajo.

**Comment by PatrikHlebecStor** [comment]
Je možno tu dodati ON/OFF za vnos vsega kupljenega v main.py?
Iskreno ne vem kaj je bolje, da vnašam vse kar kupim in prepustim davčni da ureja davčno stopnjo ter FIFO ali programu? 
Glede na to, da ima program trenutno težavo pri spreminjajočih se headerjih skozi leta, se mi zdi bolje vnesti vse kar sem kupil v letu in prepustiti eDavkom, da beleži pariteto.
Je to debato bolje premakniti kam drugam ali je na mestu?
